version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    finally:
      - echo This always runs even if the update or install command fails

  pre_build:
    commands:
      - npm pkg delete scripts.useless
      - yarn install --frozen-lockfile
    finally:
      - echo This always runs even if the login command fails

  build:
    commands:
      - yarn build
    finally:
      - echo This always runs even if the install command fails

  post_build:
    commands:
      - aws s3 sync --delete ./build s3://${DEPLOY_BUCKET}
      # - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths /index.html